#include "TIM.h"


void Init_TIM2(void){
	
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN; // Clock enable TIM2
	
	TIM2->PSC = 1599;		// Prescale 
	TIM2->ARR = 9;			// Autoreload

	
	TIM2->DIER |= TIM_DIER_UIE;
	NVIC_EnableIRQ(TIM2_IRQn);
	
	TIM2->CR1 |= TIM_CR1_CEN;		// Enable TIM2
}

void Init_TIM3(void){
	
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; //TIM3
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN; //PC7, PA6
	
	GPIOA -> MODER |= GPIO_MODER_MODER6_1; 
	GPIOA -> AFR[0] |= (2 << (6  * 4));  //AF6
	
	TIM3 -> CR1 = 0; //STOP TIMER
	TIM3 -> PSC = 16 - 1; // 84 MHZ (1ms)
	TIM3 -> ARR = 10 - 1; //16 BIT AUTO RELOAD
	TIM3 -> CR1 |= TIM_CR1_ARPE;
	
	// INPUT CAPTURE PA6
	TIM3 -> CCMR1 |= TIM_CCMR1_CC1S_0;
	TIM3 -> CCMR1 &= ~TIM_CCER_CC1P;
	TIM3 -> CCER |= TIM_CCER_CC1E;  // CAPTURE ENABLE
		
	TIM3 -> DIER |= TIM_DIER_CC1IE; //CAPTURE COMPARE INTERRUPT ENABLE
	TIM3 -> DIER |= TIM_DIER_UIE;  // UPDATE INTERRUPT
	
	NVIC_EnableIRQ(TIM3_IRQn);
	
	TIM3 -> CR1 |= TIM_CR1_CEN;  //TIM ENABLE
}
